### ISSUE TITLE
Rich List Not Displaying Correct "Rich List"

### ISSUE THREAD

**Issue by psipherious** [Nexusoft/Nexus#17]
The 'dumprichlist' API call, when queried in current 2.2.3 node, does not display a correct rich list from all wallets in existence.

Instead it "appears" to display some type of list from the system memory since that particular node has been started.

If a node is freshly restarted, all the top 10's balances will show somewhere around the size of a block reward and slowly increase as time passes and more transactions are seen by that node.

Rich List works correctly in 2.0.5, so the code error may exist in the LLD implementation.

**Comment by VidereLicet** [comment]
This is in the loading block index function you can find in index.cpp. I can make a commit to fix this on LLD versions

**Comment by VidereLicet** [comment]
Use argument -richlist for nodes from now on. Works on Oracle or LLD

https://github.com/Nexusoft/Nexus/commit/c86e2e4b40860ace32de10745e78d7f0ab0cff08
