### ISSUE TITLE
Unable to Pull Transaction Info for TX in Proof of Stake Blocks

### ISSUE THREAD

**Issue by psipherious** [Nexusoft/Nexus#18]
Both the 'gettransaction' & 'getglobaltransaction' API calls are unable to pull any information from transactions that are part of initial coinbase distribution of nProof of Stake blocks.

Valid TX ID's come back with response: "Invalid or non-wallet transaction id (code -5)" & "Invalid transaction id (code -5)" respectively.

**Comment by VidereLicet** [comment]
https://github.com/Nexusoft/Nexus/commit/014066a5ec19a5b05a5f82d92a5f846034e6e27b

Solved.
