### ISSUE TITLE
Request: API Function to Look Up TX's for Any Address

### ISSUE THREAD

**Issue by psipherious** [Nexusoft/Nexus#19]
As of current, it appears the 'listtransactions' function will only list transactions for accounts that you have within your own wallet.

Could we get the ability to list all transactions for **any** account on the entire blockchain?

It could simply be added to the existing 'listtransactions' function, no additional function should be necessary unless a 'listglobaltransactions' might make more sense?

**Comment by VidereLicet** [comment]
In getrawtransaction, getglobaltransaction, or gettransaction code.
