### ISSUE TITLE
Wallet encryption

### ISSUE THREAD

**Issue by mercuryminer** [Nexusoft/Nexus#27]
Excessively long wallet passphrases are sometimes not accepted to unlock wallet, tested with 34 character passphrase. Wallet will in some cases not unlock even when valid passphrase is entered.

**Comment by VidereLicet** [comment]
Interesting to note. Thank you for figuring this out.

**Comment by ajmcl** [comment]
Is this still an issue?

**Comment by sidnt** [comment]
Is this still an issue?

**Comment by VidereLicet** [comment]
Closed for inactivity

**Comment by sidnt** [comment]
Isn't this a critical issue?
