### ISSUE TITLE
Nexus solo mining

### ISSUE THREAD

**Issue by imrecsoka** [Nexusoft/Nexus#29]
Hi, how on earth is the solo mining setup
How do you configure the conf file and what is the proper name for the conf file
is it nexus.conf or something else.conf
and what is the content

**Comment by physicsdude** [comment]
Hi. Please don't post questions under issues. Your best bet to get help is to join the Slack - head to http://nexusearth.com:3000/ 

Also, check out this video https://www.youtube.com/watch?v=0YeKrJYrEh8&feature=youtu.be
