### ISSUE TITLE
duplicate wallets on different boxes showing different balences

### ISSUE THREAD

**Issue by joshyOcuk** [Nexusoft/Nexus#30]
i have 2 wallets running both are duplicates and should show the same balance.
one machine is acting as mining host using 127 loop back for itself the other is at a different site and is acting as a nated local mining host for everything within that nat.

one wallet is showing 103 transactions the other 107 balance in one is 182nxs the other 237nxs

somtimes i notice my miners find blocks they get submitted and excepted the transaction number goes up but 1 in 10 it seems i never receive the block reward with no entry in transaction logs.

i have deleted the blockchain and resynced on both wallets and they still show different balances and number of transaction they are the same wallet how can this be?

any help would be greatly appreciated as it stands im missing about 7 block rewards that have just vanished but show on the number of transactions on the wallet overview page

**Comment by VidereLicet** [comment]
When is the most recent time that your wallets were mirrored. The wallet.dat uses a keypool to keep a set of keys available to the user. Each new mined block draws a key from the keypool for your use. Have you attempted to run a "repairwallet" command to check for false flags in the accounting ?
