### ISSUE TITLE
getblocktemplate 

### ISSUE THREAD

**Issue by GianniExplore** [Nexusoft/Nexus#35]
./nexus getblocktemplate
error: {"code":-32601,"message":"Method not found"}

Please update getblocktemplate RPC

**Comment by barrystyle** [comment]
The blockhash is 128byte, txid (hence merkleroot) is 64byte; you're not simply going to be able to get this working in a stratum without massively modifying the stratum too.
Getblocktemplate isn't even the tip of the iceberg here..

**Comment by VidereLicet** [comment]
There isn't a getblocktenplate command. This is deprecated and replaced by the Mining LLP
