### ISSUE TITLE
Wallet Crash

### ISSUE THREAD

**Issue by Schamns** [Nexusoft/Nexus#5]
Hi!

I've left my PC mining NXS and the wallet opened too. About 48h, when I came back to check, it looks like the wallet has crashed because a lack of memory. Now every time I try to open the wallet, it crashes a few secound after the NEXUS logo shows.
I still have some NXS in there, so I wonder if someone can help me retrive them.
I was using the 2.0.3 version, tried to update to 2.0.5, but same problem is happening.

Please Help!
Schamns

**Comment by VidereLicet** [comment]
This is an issue in the solominer, and then a corruption of the block index database there after. Solo miner has been repaired, and LLD release coming next to solve the index corruption. Refer to slack at http://nexusearth.com:3000 for support.
