### ISSUE TITLE
nexus-qt wallet crashes during start

### ISSUE THREAD

**Issue by oiron700ak** [Nexusoft/Nexus#51]
Running Ubuntu 17.10 on AMD phenom ii 1065T, 64 bit. (I know, it's an old chip). Installed everything as stated in Nexus wallet tutorial for Linux. When trying to start wallet, I get the Nexus Logo for several seconds, then it crashes before finishing I get this list of errors: 
./nexus-qt: Symbol `__shm_directory' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `__shm_directory' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `strlen' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `strlen' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `strchr' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `strchr' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `__mempcpy' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `__mempcpy' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `memcpy' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `memcpy' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `pthread_setcancelstate' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `pthread_setcancelstate' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `open' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `__stack_chk_fail' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `__stack_chk_fail' causes overflow in R_X86_64_PC32 relocation
./nexus-qt: Symbol `unlink' causes overflow in R_X86_64_PC32 relocation
Could not parse stylesheet of widget 0x7fff880ae760
libpng warning: iCCP: known incorrect sRGB profile
No systemtrayicon available
libpng warning: iCCP: known incorrect sRGB profile
Segmentation fault (core dumped)

It seems that the "causes overflow in R_X86_64_PC32 relocation" has to do with converting address space to 64 bit, for the AMD architecture. But I don't know where to go from there.

**Comment by warped-ch** [comment]
I had the same issue, either wait for pull request #52 being merged or build the wallet with `CONFIG+=release` instead of `"RELEASE=1"`. Fixed the startup crash for me.

**Comment by oiron700ak** [comment]
Thanks, warped-ch! That solution worked.
