### ISSUE TITLE
linking errors

### ISSUE THREAD

**Issue by norayr** [Nexusoft/Nexus#53]
I am trying to build this on gentoo, and first problem I had and solved was that the db_cxx.h file was not found, I have solved it by adding '-I/usr/include/db5.3' to the INCPATH in the Makefile.

Next, now it does not link:

```
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lboost_filesystem
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lboost_program_options
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lboost_thread
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lssl
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lcrypto
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lminiupnpc
collect2: error: ld returned 1 exit status
makefile.unix:219: recipe for target 'nexus' failed
make: *** [nexus] Error 1

```
same problem with gui and commandline versions.
i have tried also gcc 6.3.0, same result.
but I do have those libraries. in /usr/lib64 most of them.
let's say:
```
# cd /usr/lib64
# find . | grep boost_filesystem
./libboost_filesystem.so
./libboost_filesystem-mt.so
./libboost_filesystem.so.1.63.0
```

what shell I do?

**Comment by VidereLicet** [comment]
Those are linkers to boost, openssl, and miniupnp. Have you built them and linked them with the proper variables in the makefile? $(BOOST_INCLUDE_PATH), etc. ?

**Comment by vrantanen** [comment]
The makefile tries to do static linking to those libraries, but you don't have the static libraries with the extension .a, but only the dynamic .so libs.

My guess is that Gentoo only supports dynamic linking (at least by default). I had the same issue with Arch Linux.

You could try editing the makefile.unix by commenting out the lines where LMODE and LMODE2 variables are defined as "static" and leaving the earlier lines where they are "dynamic".

Not sure if it works. For convenience I compile static binaries in an Ubuntu virtual machine.

**Comment by VidereLicet** [comment]
Closed for inactivity.
