### ISSUE TITLE
./nexus command, process seems to be stuck

### ISSUE THREAD

**Issue by oiron700ak** [Nexusoft/Nexus#54]
when attempting to execute the daemon, nothing appears to happen, except for a lone cursor on the next line. Something is running, because I can stop the process with 'ctrl C'. When using the command "./nexus getblock", I get the message "error: couldn't connect to server". Also, when attempting to launch the miner, I get the message "Failed to Connect to Mining LLP Server...". I'm guessing that these are related. The nexus-QT wallet does open and it did update and shows connections, but it opens with a few errors and nothing is selectable out of the menus. I am running Ubuntu 17.10

**Comment by VidereLicet** [comment]
Run it with -printtoconsole and -verbose=2 if you want to see debug output. It takes a minute to boot up the node.

**Comment by bibbityjibbity** [comment]
Use htop to keep track of it's memory usage. It opens generally when memory usage hits 1500-1600MB. If you don't have htop, *sudo apt-get install htop iotop*. They're very useful tools

**Comment by VidereLicet** [comment]
Marking issue as resolved
