### ISSUE TITLE
Linux Compiling Issue

### ISSUE THREAD

**Issue by schultzynj** [Nexusoft/Nexus#63]
Hi Colin,

Getting these errors when compiling the new wallet..
Older ones worked fine.
All dependencies are up to date.

Got this problem with qmake
nic@nic-desktop:~/Nexus$ qmake nexus-qt.pro RELEASE=1 USE_UPNP=1

Project MESSAGE: Building with Static Linking
Project MESSAGE: Building with UPNP support
Project MESSAGE: Building with Lower Level Database Support
Warning: ignoring <defaultcodec> element
Warning: ignoring <defaultcodec> element
Warning: ignoring <defaultcodec> element
Warning: ignoring <defaultcodec> element
Warning: ignoring <defaultcodec> element
Warning: ignoring <defaultcodec> element

When 'make'
Is it a qt problem?
nic@nic-desktop:~/Nexus$ make

g++ -c -m64 -pipe -fstack-protector -D_FORTIFY_SOURCE=2 -fpermissive -O2 -w -D_REENTRANT -fPIC -DQT_GUI -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DUSE_UPNP=1 -DSTATICLIB -DUSE_LLD -DLINUX -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -Isrc -Isrc/core -Isrc/hash -Isrc/json -Isrc/keys -Isrc/net -Isrc/qt -Isrc/util -Isrc/wallet -Isrc/LLD -Isrc/LLP -isystem /usr/include/boost -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o build/obj/main-qt.o src/qt/main-qt.cpp

In file included from src/qt/main-qt.cpp:9:0:
src/qt/core/gui.h:12:23: fatal error: QMainWindow: No such file or directory
compilation terminated.
Makefile:1217: recipe for target 'build/obj/main-qt.o' failed
make: *** [build/obj/main-qt.o] Error 1

**Comment by bibbityjibbity** [comment]
you have qt5 installed. the source doesnt compile with it yet, but i'll be pushing my fork in a couple days which will allow it to compile with qt4 and qt5. check back in a couple days

**Comment by gruvin** [comment]
For anyone else with Qt5 already installed and not wanting to remove it ...

```
Nexus$ sudo apt-get install qt4-default qt4-qmake libqt4-dev
Nexus$ qmake-qt4 nexus-qt.pro "RELEASE=1" "USE_UPNP=1"
```

... should get you there.

**Comment by VidereLicet** [comment]
Resolved
