### ISSUE TITLE
Problem compiling

### ISSUE THREAD

**Issue by resistance-is-futile** [Nexusoft/Nexus#66]
```
src/wallet/../core/../util/bignum.h: In function ‘bool operator<(const CBigNum&, const CBigNum&)’:
src/wallet/../core/../util/bignum.h:688:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 inline bool operator<(const CBigNum& a, const CBigNum& b)  { return (BN_cmp(&a, &b) < 0); }
```
I believe it may have to do with openssl.

**Comment by bibbityjibbity** [comment]
Yes. that's a result of compiling with Openssl 1.1.X verions. the code for openssl changed drastically from 1.0.X to 1.1.X versions. It's a major undertaking to migrate to the new one, so I haven't had a chance to yet, but its the last dependency left I need to update through our source. In the mean time, you can usually install openssl1.0.X versions and them manually link the libssl and libcrypto files during compilation.

**Comment by VidereLicet** [comment]
Closed as resolved. Use apt-get install libssl1.0-dev
