### ISSUE TITLE
Could not parse stylesheet of widget 0x7ffd5579b53

### ISSUE THREAD

**Issue by x9N3XHRcpg7iEL7QRH** [Nexusoft/Nexus#67]
debian build 0.2.3.5
Message "Could not parse stylesheet of widget 0x7ffd5579b53"  when ./nexus-qt executes
No File/ Settings options menu
Blockchain loads and client connects to network but can't encrypt or back wallet becuase the menu is missing

**Comment by resistance-is-futile** [comment]
So on ubuntu you need to access the menu using 'alt' then type out what you want. So Encrypt and it should show the menu option at the top of the screen

**Comment by x9N3XHRcpg7iEL7QRH** [comment]
Thanks for the fast reponse:
"alt' key isn't doing anything for me
and yes its ubuntu 16.04

**Comment by x9N3XHRcpg7iEL7QRH** [comment]
also I moved an encrypted wallet.dat from windows install and there is still no menu
I held alt down and tried all the super and control and function key combinations too

**Comment by resistance-is-futile** [comment]
Just pressing alt should prompt you with a search box. You don't have to hold it down.

**Comment by x9N3XHRcpg7iEL7QRH** [comment]
OK I got to the menu option...encrpted the wallet and after the reboot the menu is still not there.   I think problem is in the QT source or the make file and might be something as simple as a path.   Could not parse stylesheet of widget 0x7fff310dcc40  I'm not a coder or i'd fix it a push it to you but thanks for geting me a menu I can work with

**Comment by resistance-is-futile** [comment]
It's a problem with your window settings on Ubuntu lookup how to show the menu on the window

**Comment by x9N3XHRcpg7iEL7QRH** [comment]
I have it set to show the menu at the top on each applications main window..and it does that for every other application.
--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com <https://tutanota.com>

21. Mar 2018 04:14 by notifications@github.com <mailto:notifications@github.com>:

**Comment by bibbityjibbity** [comment]
I've resolved the stylesheet and png errors and the menu is fully functional in the upcoming release using qt5
