### ISSUE TITLE
wallet does not synchronize, storage not visible

### ISSUE THREAD

**Issue by gabriele70** [Nexusoft/Nexus#68]
the synchronization of my wallet does not seem to go, since days tells me that it is stuck to block 1859096, the deposit made by bitterx is obviously not visible. I'm not an expert. Please help me with simple words

![address of receive](https://user-images.githubusercontent.com/37598685/37683361-ab5208f2-2c8c-11e8-803d-81b596beb31b.PNG)
1859096

**Comment by VidereLicet** [comment]
Please address this in slack support. It has been resolved.
