### ISSUE TITLE
menu options on Ubuntu 16.04 

### ISSUE THREAD

**Issue by x9N3XHRcpg7iEL7QRH** [Nexusoft/Nexus#70]
I still have to hit "alt" to pull up the file option etc. on the 0.2.4.1 build
I don't know what to type in the search bar if i want to import/export a key
Since the "fix" didn't work, maybe you could supply a map of what the menu options are so I can use nexus-qt

**Comment by bibbityjibbity** [comment]
Try doing a

* sudo apt-get remove appmenu-qt5

and restart. Let me know if that takes care of it.

**Comment by x9N3XHRcpg7iEL7QRH** [comment]
Yes.  That worked!  Thank you.

And I now see the options are just the btc core options too.   I guess I was used to using armory on top of it for bitcoin.
--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com <https://tutanota.com>

10. Apr 2018 14:00 by notifications@github.com <mailto:notifications@github.com>:
