### ISSUE TITLE
compiling error: BIGNUM on qt, EVP_CIPHER_CTX

### ISSUE THREAD

**Issue by breathlessvix** [Nexusoft/Nexus#74]
Hello, I receive a compiling error when installing the wallet and the qt wallet on fresh distro installs. Here are the Ubuntu outputs, I already wiped the Debian install but neither wallet worked there either.
Please fix. I'd like to be able to actually use a currency before I do any investing.
https://gist.github.com/breathlessvix/29deb99a794fffc8edb4a450ce7d71f1

**Comment by jamesbrink** [comment]
@breathlessvix looks like you are on Ubuntu Linux. You will need to install OpenSSL 1.0 which is pretty straight forward.

`sudo apt-get install libssl1.0-dev`

After installing that give it a try again.

**Comment by breathlessvix** [comment]
It is Ubuntu, a fresh install.
Installed the older libssl package like you said to, nexus-qt launched and seemed like it started to work. Stopped it and and then extracted the database files in place, launched it again. It took about an hour to launch, I don't think it downloaded anything though. Had ~10 connections. Left it to sit for a few hours, was still stuck on the same block I believe.
Deleted the zipped database. Let it run again. Took a few minutes to launch. Seemed to get stuck a few times, had to shut it down. It got about halfway (~900k remaining I think) before it got stuck for good. Let it sit for a few hours, restarted it, no progress.
Didn't change anything, just left this computer to rest, came back and now it is segfaulting after showing the Initializing LLD Keychains... phase. 
`anon@local:~/Nexus$ ./nexus-qt 
Segmentation fault (core dumped)
anon@local:~/Nexus$ ./nexus-qt 
Segmentation fault (core dumped)
anon@local:~/Nexus$ ./nexus-qt 
Segmentation fault (core dumped)`
Restarted the computer, started nexus-qt, it didn't segfault but its been running ~15 minutes and I haven't seen the window yet. Hasn't printed anything to console either.

**Comment by breathlessvix** [comment]
Sorry meant to say it did show the splashscreen but it disappeared rather quickly compared to what it was shown for, have not seen the main window.
0.2.4.4

**Comment by breathlessvix** [comment]
Additionally it seemed to download at a pace of about half a second for every 10 blocks regardless of when it just connected to the first or when it had 14 connections (most I saw).

**Comment by breathlessvix** [comment]
~150k left. Froze there and I came back after an hour and it was still there. Stopped it, started again and it's been at Initializing Keychains for multiple hours now... would be nice to know how much each phase is supposed to take with an almost full database on modern hardware...

**Comment by breathlessvix** [comment]
Day 8. All I get is initializing keychains when I start now. Does the wallet actually work under debian or would that be a waste of my time?

**Comment by breathlessvix** [comment]
Thank you all for the help. Hopefully by this time next year you'll release a working wallet. Onto other projects now.
