### ISSUE TITLE
Sync problem

### ISSUE THREAD

**Issue by Berensbach** [Nexusoft/Nexus#83]
I have tried to sync my wallet in 3 different PCs and it stops after a while.

**Comment by bibbityjibbity** [comment]
Are you using version 2.4.6? Also, is it stopping on the same block each time or a different block?

**Comment by akseeker** [comment]
Sync stopped for me, too, seemed to hang with 139 blocks remaining, restarted nexus-qt v.2.5.3, sitting with last generated block 1 day ago,, 2291909, 14 connections...

**Comment by VidereLicet** [comment]
Resolved in 2.5.0 +
