### ISSUE TITLE
makefile.unix dones not exist

### ISSUE THREAD

**Issue by fmarines** [Nexusoft/Nexus#84]
I'm trying to compile this on centos 7.5 is this feasible? ...the makefile.unix does not exists

**Comment by bibbityjibbity** [comment]
that document is old. i consolidated the different CLI version makefiles into a single OS-detecting one name `makefile.cli`. try following the instructions and using that one instead. if you get errors when compiling, please post the output here.

**Comment by fmarines** [comment]
not sure if i need to install a dependancy but i got this error during compile
---------------------------------------------------------------
 make -f makefile.cli
Compiling src/core/version.cpp
Compiling src/net/netbase.cpp
Compiling src/net/addrman.cpp
Compiling src/wallet/crypter.cpp
Compiling src/wallet/key.cpp
Compiling src/wallet/db.cpp
In file included from src/wallet/db.cpp:9:0:
src/wallet/db.h:18:20: fatal error: db_cxx.h: No such file or directory
 #include <db_cxx.h>
                    ^
compilation terminated.
make: *** [build/db.o] Error 1

**Comment by fmarines** [comment]
searching around seems this to be related with Berkley DB but i have that installed...and more
yum list installed |grep libdb
libdb.x86_64                          5.3.21-24.el7              @base
libdb-devel.x86_64                    5.3.21-24.el7              @base
libdb-utils.x86_64                    5.3.21-24.el7              @base
libdb4.x86_64                         4.8.30-13.el7              @epel
libdb4-devel.x86_64                   4.8.30-13.el7              @epel

**Comment by fmarines** [comment]
yum install libdb-cxx* (this libraries were missing)
