### ISSUE TITLE
NEXUS-QT -  ld cannot find -lminiupnpc ,cannot find -ldb_cxx , ld: cannot find -lssl , ld: cannot find -lcrypto

### ISSUE THREAD

**Issue by fmarines** [Nexusoft/Nexus#86]
Hi, during compilation of nexus -qt  on Centos 7  make fails linking to dependencies:
-------------------------------------
**qmake nexus-qt.pro "RELEASE=1" "USE_UPNP=0" "VERBOSE=1"**
Project MESSAGE: Showing Verbose Output
Project MESSAGE: Building 64-Bit Version
Project MESSAGE: Building Release Version
Project MESSAGE: Building with Static Linking
Project MESSAGE: Building with UPNP support
Project MESSAGE: Building with Lower Level Database Support
Project MESSAGE: Translations Generated
Project MESSAGE: Finishing up... Type 'make' to start compiling when finished
-----------------------------------------------------
**make VERBOSE=1**
/usr/lib64/qt4/bin/rcc -name nexus src/qt/nexus.qrc -o qrc_nexus.cpp
g++ -c -pipe -std=c++11 -m64 -fstack-protector -s -D_FORTIFY_SOURCE=2 -fpermissive -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -w -D_REENTRANT -DQT_GUI -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -Dx64 -DNDEBUG -DUSE_UPNP=1 -DMINIUPNP_STATICLIB -DUSE_LLD -DLINUX -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/lib64/qt4/mkspecs/linux-g++ -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -Isrc -Isrc/core -Isrc/hash -Isrc/json -Isrc/net -Isrc/qt -Isrc/util -Isrc/wallet -Isrc/LLD -Isrc/LLP -I/usr/include/miniupnpc -I/usr/local/include/boost -I/usr/include -I/usr/include/openssl -Ibuild/moc -Ibuild/ui -o build/obj/qrc_nexus.o qrc_nexus.cpp

Finished Building nexus-qt

g++ -m64 -fstack-protector -s -Wl,-O1 -Wl,-z,relro -o nexus-qt build/obj/block.o build/obj/dispatch.o build/obj/message.o build/obj/transaction.o build/obj/mining.o build/obj/checkpoints.o build/obj/main-qt.o build/obj/gui.o build/obj/transactiontablemodel.o build/obj/addresstablemodel.o build/obj/optionsdialog.o build/obj/sendcoinsdialog.o build/obj/addressbookpage.o build/obj/messagepage.o build/obj/aboutdialog.o build/obj/editaddressdialog.o build/obj/addressvalidator.o build/obj/version.o build/obj/difficulty.o build/obj/prime.o build/obj/debug.o build/obj/util.o build/obj/netbase.o build/obj/key.o build/obj/script.o build/obj/skein.o build/obj/skein_block.o build/obj/KeccakDuplex.o build/obj/KeccakSponge.o build/obj/Keccak-compact64.o build/obj/KeccakHash.o build/obj/net.o build/obj/addrman.o build/obj/release.o build/obj/unifiedtime.o build/obj/db.o build/obj/walletdb.o build/obj/json_spirit_writer.o build/obj/json_spirit_value.o build/obj/json_spirit_reader.o build/obj/clientmodel.o build/obj/guiutil.o build/obj/transactionrecord.o build/obj/optionsmodel.o build/obj/monitoreddatamapper.o build/obj/transactiondesc.o build/obj/transactiondescdialog.o build/obj/strings.o build/obj/amountfield.o build/obj/wallet.o build/obj/keystore.o build/obj/transactionfilterproxy.o build/obj/transactionview.o build/obj/walletmodel.o build/obj/rpcserver.o build/obj/rpcdump.o build/obj/overviewpage.o build/obj/csvmodelwriter.o build/obj/crypter.o build/obj/sendcoinsentry.o build/obj/qvalidatedlineedit.o build/obj/units.o build/obj/qvaluecombobox.o build/obj/askpassphrasedialog.o build/obj/protocol.o build/obj/notificator.o build/obj/qtipcserver.o build/obj/rpcconsole.o build/obj/kernel.o build/obj/main.o build/obj/global.o build/obj/keychain.o build/obj/trustkeys.o build/obj/index.o build/obj/moc_gui.o build/obj/moc_transactiontablemodel.o build/obj/moc_addresstablemodel.o build/obj/moc_optionsdialog.o build/obj/moc_sendcoinsdialog.o build/obj/moc_addressbookpage.o build/obj/moc_messagepage.o build/obj/moc_aboutdialog.o build/obj/moc_editaddressdialog.o build/obj/moc_addressvalidator.o build/obj/moc_clientmodel.o build/obj/moc_optionsmodel.o build/obj/moc_monitoreddatamapper.o build/obj/moc_transactiondesc.o build/obj/moc_transactiondescdialog.o build/obj/moc_amountfield.o build/obj/moc_transactionfilterproxy.o build/obj/moc_transactionview.o build/obj/moc_walletmodel.o build/obj/moc_overviewpage.o build/obj/moc_csvmodelwriter.o build/obj/moc_sendcoinsentry.o build/obj/moc_qvalidatedlineedit.o build/obj/moc_qvaluecombobox.o build/obj/moc_askpassphrasedialog.o build/obj/moc_notificator.o build/obj/moc_rpcconsole.o build/obj/qrc_nexus.o    -L/usr/lib64 -Wl,-Bstatic -L/usr/lib64 -lminiupnpc -L/usr/local/lib -ldb_cxx -lboost_system -lboost_filesystem -lboost_program_options -lboost_thread -lssl -lcrypto -Wl,-Bdynamic -ldl -lrt -lpthread -lQtGui -lQtCore
/usr/bin/ld: cannot find -lminiupnpc
/usr/bin/ld: cannot find -ldb_cxx
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
make: *** [nexus-qt] Error 1

**Comment by bibbityjibbity** [comment]
I'll go through and update documentation this week for various OS's. I'm thinking centos, ubuntu, debian, mint, arch, kali, gentoo, and freebsd. That will cover both the most popular distros as well as the main package managers (dnf/yum, apt, pacman, portage, and ports). If you have any suggestions for additional ones, let me know.

As for your issue in the meantime, if you've installed the libminiupnpc-dev, libdb++-dev, and libssl-dev packages, then its likely they don't have static libraries built in the repos centos uses. edit the Makefile and by LIBS, remove "-Wl,-Bstatic" from the line. then do 'make clean' and 'make' again. don't rerun qmake or else it'll just overwrite your makefile again.

**Comment by fmarines** [comment]
that did the trick! to be more specific i've modified the nexus-qt.pro removing the options, leaving the LIBS= blank, then make clean and make again. after few mins i got the  **Finished Building nexus-qt**

thanks a lot.
