### ISSUE TITLE
wallet is not staking

### ISSUE THREAD

**Issue by winstonstallacs** [Nexusoft/Nexus#93]
I installed the latest version of the wallet for windows and used a backup file from the older wallet version to restore the wallet. 
The wallet synced with the network rather quickly and it stays up-to-date but it hasn't been staking for last 5 days! 
No new transactions have been posted.
Anybody knows what the problem may be...? 
I'd greatly appreciate any input and/or suggestions. 
Thx in advance! 
Winston

**Comment by dbigge** [comment]
Possible issue-  Did you backup the wallet before or after you staked?  I think there is a caveat about creating a post genesis transaction copy of your wallet for staking.  If you are restoring a pre-staking wallet that may be the problem.

**Comment by VidereLicet** [comment]
Is this still an issue?

**Comment by VidereLicet** [comment]
Closed due to inactivity
