### ISSUE TITLE
wallet does not receiving any transaction

### ISSUE THREAD

**Issue by dzikuseknj** [Nexusoft/Nexus#95]
I just got my wallet all set up and encrypted and I am trying to send my coins from Binance to my wallet but transfers are getting recjected ... why ? what may cost that issue ?

**Comment by dbigge** [comment]
Binance had some NXS wallet maintenance going on yesterday.  I couldn't transfer out at all for a few hours.  That cleared up this morning.  Are you still having the issue?  Where are you seeing rejection of the transfer?

**Comment by dzikuseknj** [comment]
yes it must be becouse binance wallet maintenance ...
I did some transfers yesterday from other exchange like Cryptopia and
everything was fine
I will try binance again later on today ...

**Comment by VidereLicet** [comment]
What's your wallet version you are running?

**Comment by VidereLicet** [comment]
Great, I'll close this issue then.
