### ISSUE TITLE
problem with wallet

### ISSUE THREAD

**Issue by dzikuseknj** [Nexusoft/Nexus#96]
I just downloaded version 2.5.5
I am using windows
when I run the newest version it started to download blocks of transaction history from the beginning, but it stops at 116 blocks and does not go any further, it shows 0 balance on my wallet ... I am kinda scared
any idea what happened and what to do ?

**Comment by VidereLicet** [comment]
Join slack at https://join.slack.com/t/nexusearth/shared_invite/enQtNDUzNDIxOTU4NTUxLTY0MjhlYjA1MjA2MGQyMzEyYWM0ZDM5ODBiOWUwZmY1YzI2Njk0YzI0MTM3MDAwYzlmMDNkZjZjYWY5ZjYxNmM and join #support to get further assistance.
